Добавление до 5 фотографий в коливинге
Studio-Yandex-Practicum/coliving_bot pull request #105
Opened 2024-03-15 16:55 UTC by VladErm91

1. Добавлена возможность сохранения до 5 фотографий в коливинге
2. Добавлена возможность изменения фотографий в коливинге
3. Также в service.py вынес в отдельную функцию сохранение фотографий.

2024-03-20 09:01 UTC, ArtemKAF commented
Вцелом работает, но при отправке 5-ти и более фотографиий бот никак на это не реагирует, а ждет нажатия кнопки. При таком подходе было бы лучше более явно указать пользователю, что бот будет до победного ждать нажатия кнопки, которая "убежит вверх" и создает "неудобства" когда пользователь отдельно загружает фотографии по одной.
Можно попробовать боту реализовать автоматическую обработку фотографий по достижении 5 штук. Тоесть попробовать реализовать алгоритм таким образом, чтобы не требовалось нажимать кнопку как только будет принято от пользователя первые 5 фотографий.

2024-03-20 09:02 UTC, ArtemKAF reviewed
Вцелом работает, но при отправке 5-ти и более фотографиий бот никак на это не реагирует, а ждет нажатия кнопки. При таком подходе было бы лучше более явно указать пользователю, что бот будет до победного ждать нажатия кнопки, которая "убежит вверх" и создает "неудобства" когда пользователь отдельно загружает фотографии по одной.
Можно попробовать боту реализовать автоматическую обработку фотографий по достижении 5 штук. Тоесть попробовать реализовать алгоритм таким образом, чтобы не требовалось нажимать кнопку как только будет принято от пользователя первые 5 фотографий.

2024-03-21 17:33 UTC, VladErm91 commented
Доработал реализацию, теперь если загружены 5 изображений то происходит автоматическая обработка и сохранение фотографий

2024-03-23 08:01 UTC, VladErm91 commented
Сделал небольшой рефакторинг, сделал один handler для добавления и изменения изображений вместо двух

2024-03-23 16:54 UTC, TomatoInOil requested changes

2024-03-23 16:54 UTC, TomatoInOil commented on src/bot/conversations/coliving/callback_funcs.py
> +        await update.effective_message.reply_text(text=templates.ERR_PHOTO_LIMIT_TEXT)
Если мы в функции `handle_add_or_edit_photo_room` прерываем обработку получаемых фотографии на 5-ой, то это условие никогда не выполнится.

2024-03-23 16:54 UTC, TomatoInOil commented on src/bot/conversations/coliving/callback_funcs.py
> +) -> None:
При объединении возникли баги:
1. Если при создании коливинга мы введём текст, а не фотографию, то после вывода сообщения о том, что бот ожидает получить фотографию, мы перейдем из состояния PHOTO_ROOM на EDIT_PHOTO_ROOM вот здесь:
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/0c776e78bb276d158bd7302ae1f60659b7b4666c/src/bot/conversations/coliving/callback_funcs.py#L311-L313
Вместо этого нужно вернуться None, что оставит нас в том же состоянии, в котором сейчас находимся 
2. Во время создания здесь должна вызываться функция `send_received_room_photos`, а не `send_edited_room_photos`
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/0c776e78bb276d158bd7302ae1f60659b7b4666c/src/bot/conversations/coliving/callback_funcs.py#L319-L321
Поэтому если мы загрузим при создании все 5 фотографий, то это приведёт в конце концов к исключению: `Client error '404 Not Found' for url 'http://127.0.0.1:8000/api/v1/users/1389394124/colivings/None/images/'`

2024-03-23 16:54 UTC, TomatoInOil commented on src/bot/conversations/coliving/callback_funcs.py
Думаю, что эти строки здесь лишние, странное сообщение выводится после "Хорошо, анкета не изменилась."
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/0c776e78bb276d158bd7302ae1f60659b7b4666c/src/bot/conversations/coliving/callback_funcs.py#L689-L694

2024-03-24 06:43 UTC, VladErm91 commented
Сделал откат изменений и внес необходимые правки

2024-03-25 10:24 UTC, TomatoInOil approved these changes

2024-03-25 10:24 UTC, merged