Add tests refactoring to ReportMatchViewTests
Studio-Yandex-Practicum/coliving_bot pull request #110
Opened 2024-03-24 13:06 UTC by ilililililililililililililil

привет,

Посмотри мою версию плз, напиши, если увидишь, где можно лучше

хотел дополнительно еще оптимизировать определение
cls.expected_match_data_for_user_*

через
ExpMatchData = namedtuple("ExpMatchData",
[cls.TID_T, cls.NAME_T, cls.AGE_T, cls.L_T])

но не уверен, стоит ли ...

2024-03-31 19:30 UTC, TomatoInOil requested changes

2024-03-31 19:30 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +    NAME_T = "name"
Можно более подробно прописать названия, например, если встретить L_T где-то в коде, то с ходу не поймёшь о чём речь.

2024-03-31 19:46 UTC, ilililililililililililililil commented on src/backend/search/tests/test_views.py
> +    NAME_T = "name"
Скорректировал

2024-04-03 08:05 UTC, TomatoInOil approved these changes

2024-04-03 08:05 UTC, merged