Feature/101 add command cancel
Studio-Yandex-Practicum/coliving_bot pull request #114
Opened 2024-03-27 08:24 UTC by Angelina91

2024-04-04 12:30 UTC, TomatoInOil requested changes

2024-04-04 12:30 UTC, TomatoInOil commented on src/bot/conversations/profile/handlers.py
>          ),
Если вызывать команду /cancel, то ничего не происходит. 
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/f5bc39cb-9683-466f-9ea7-ff320d339253)
Команды обрабатываются [CommandHandler](https://docs.python-telegram-bot.org/en/latest/telegram.ext.commandhandler.html#commandhandler)
Использование есть в этом [примере](https://docs.python-telegram-bot.org/en/latest/examples.conversationbot.html), в 156-й строке

2024-04-04 12:30 UTC, TomatoInOil commented on src/bot/conversations/menu/templates.py
>  }
Давай назовём попроще: "Отмена"

2024-04-04 12:30 UTC, TomatoInOil commented on src/bot/conversations/profile/handlers.py
>          ),
Вторая недоработка из скриншота: нужно убрать кнопку отмена, она больше нам не пригодится. В этом заключается цель таски: заменить кнопку на команду, потому что команда всегда доступна, её не нужно добавлять к каждому сообщению, это намного удобнее и для разработчиков и для пользователя.

2024-04-13 11:48 UTC, Aqua178 commented
Реализовал поставленную задачу, жду обратную связь.

2024-04-13 13:40 UTC, TomatoInOil approved these changes

2024-04-13 14:00 UTC, merged