Feature/98 add notification after create mr
Studio-Yandex-Practicum/coliving_bot pull request #115
Opened 2024-03-27 08:26 UTC by Angelina91

2024-04-16 17:33 UTC, TomatoInOil requested changes

2024-04-16 17:33 UTC, TomatoInOil commented on src/bot/conversations/match_requests/templates.py
> +)
Смысл в том, чтобы мы передали контакты этих людей друг другу. То есть вместо `{profile.name}` должен быть `@{username}`
Чтобы его получить можно использовать 
```Python
chat = await context.bot.get_chat(chat_id=telegram_id)
chat.username
```

2024-04-16 20:59 UTC, TatianaBelova333 commented on src/bot/conversations/match_requests/templates.py
> +)
А как быть, если у пользователя нет username? Username же необязателен для профиля телеграмм....

2024-04-16 21:04 UTC, TatianaBelova333 commented on src/bot/conversations/match_requests/templates.py
> +)
Может тогда надо добавить поле с номером телефона в модели профиля пользователя?

2024-04-21 18:16 UTC, TomatoInOil approved these changes

2024-04-21 18:16 UTC, merged