Added 'ANY_GENDER_BTN' option to sex search
Studio-Yandex-Practicum/coliving_bot pull request #127
Opened 2024-04-05 17:52 UTC by StriderDunedain

2024-04-09 07:05 UTC, TomatoInOil requested changes
У тебя есть проблемы с запуском проекта? Если есть, то обязательно обратись за помощью в Пачку. Разрабатывать без возможности запустить проект и пощупать, что накодил, крайне сложно.

2024-04-09 07:05 UTC, TomatoInOil commented on src/bot/conversations/roommate_search/handlers.py
> +                """,
Такой перенос не работает, потому что результатом используемом в `pattern` будет
```Python
re.compile('\n                    ^(Парень|Девушка|Неважно)$\n                ')
```
, используй перенос таким образом
```Python
<...>
pattern=(
    rf"^({buttons.MALE_BTN}"
    f"|{buttons.FEMALE_BTN}"
    f"|{buttons.ANY_GENDER_BTN})$"
),
<...>
```
Тогда ты получишь 
```Python
re.compile('^(Парень|Девушка|Неважно)$')
```

2024-04-09 07:05 UTC, TomatoInOil commented on src/bot/conversations/roommate_search/handlers.py
> +                """,
После этого исправления запусти проект и попробуй использовать новый функционал, над которым ты работаешь.  
В таком случае ты получишь исключение: `httpx.HTTPStatusError: Client error '400 Bad Request' for url <...>`
С ответом от API: `Content: {"sex":["Выберите корректный вариант. Неважно нет среди допустимых значений."]}`
Как это исправить? 
Второй пункт твоей задачи
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/7e5207ee-d16d-4e8a-883d-601e58d1f385)

2024-04-11 07:03 UTC, StriderDunedain commented
Получается, надо оставить `sex: None` в самой анкете поиска? Выглядит не очень user-friendly, а как сделать так, чтобы там отображалось само `Неважно`? Или это сложно поменять? Я не работал много с ботами, но разве это поле не просто строка и не особо важно, что в нее записано, пока по ней можно искать соседа? То есть где бот понимает, что такая строка валидная. Я пытался найти этот код, но не пойму, где он. help please

2024-04-11 07:07 UTC, StriderDunedain commented on src/bot/conversations/roommate_search/handlers.py
> +                """,
Получается, надо оставить `sex: None` в самой анкете поиска? Выглядит не очень user-friendly, а как сделать так, чтобы там отображалось само `Неважно`? Или это сложно поменять? Я не работал много с ботами, но разве это поле не просто строка и не особо важно, что в нее записано, пока по ней можно искать соседа? То есть где бот понимает, что такая строка валидная. Я пытался найти этот код, но не пойму, где он. help please

2024-04-11 09:35 UTC, TomatoInOil commented on src/bot/conversations/roommate_search/handlers.py
> +                """,
Дело в том, что в текущей реализации API query-параметр sex принимает значения "Парень" и "Девушка", но значение "Неважно" приведёт к `Bad Request` с сообщением `Content: {"sex":["Выберите корректный вариант. Неважно нет среди допустимых значений."]}`. 
Что мы хотим, когда пользователь отвечает "Неважно"? Мы хотим, чтобы queryset не фильтровался по данному атрибуту. Что мы можем для этого сделать? Не передавать соответствующий query-параметр в запросе. 
Если мы посмотрим на эту строку
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/a1e9a95bfc2ce145b25acaf5b5fbee5d955d6eb3/src/bot/internal_requests/service.py#L166
То увидим, что обёртка API уже не будет передавать query-параметры для которых выставлены значения None
Это означает, что в экземпляре ProfileSearchSettings, который мы передаём в аргументах этого метода нам нужно выставить оставить sex=None. 
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/a1e9a95bfc2ce145b25acaf5b5fbee5d955d6eb3/src/bot/internal_requests/service.py#L156-L158
Как ты правильно заметил, `Выглядит не очень user-friendly, а как сделать так, чтобы там отображалось само Неважно?` 
Нужно отредактировать функцию, которая отвечает за формирование сообщения 
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/eb34a646e8a301fcd0c88983f61d5c8ed6a5d819/src/bot/conversations/roommate_search/templates.py#L39-L51

2024-04-11 12:19 UTC, StriderDunedain commented on src/bot/conversations/roommate_search/handlers.py
> +                """,
Добавил `if`'ку для `Неважно`. Спасибо, что объяснил, что к чему :)

2024-04-11 12:26 UTC, StriderDunedain commented on src/bot/conversations/roommate_search/handlers.py
> +                """,
Ладно, отмена, оно не работает так)

2024-04-11 13:01 UTC, StriderDunedain commented on src/bot/conversations/roommate_search/handlers.py
> +                """,
А, все, разобрался. Но не очень уверен, что так стоит делать. Если такой фокус с f-строкой прокатывает, то норм, а если менять значение `filters.sex`, то все ломается на более поздних этапах

2024-04-12 14:32 UTC, TomatoInOil approved these changes

2024-04-12 14:32 UTC, merged