Add profiles tests refactoring (test_profiles)
Studio-Yandex-Practicum/coliving_bot pull request #129
Opened 2024-04-06 14:51 UTC by ilililililililililililililil

Add some profiles tests improvements/refactoring (test_profiles)

2024-04-09 12:29 UTC, ilililililililililililililil commented
@TomatoInOil 👋

2024-04-10 08:42 UTC, TomatoInOil requested changes

2024-04-10 08:42 UTC, TomatoInOil commented on src/backend/profiles/tests/test_profiles.py
>          )
Из-за этой настройки
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/dcf6607c063a74913d2de386a20877c0a33cebc6/src/backend/coliving_bot/settings/base.py#L118-L119
Нам не нужно указывать format в каждом запросе, он по умолчанию будет `"json"`

2024-04-13 14:26 UTC, TomatoInOil approved these changes

2024-04-13 14:26 UTC, merged