Add prefix response and magic numbers
Studio-Yandex-Practicum/coliving_bot pull request #130
Opened 2024-04-07 10:54 UTC by TatianaBelova333

1) Написала декоратор по отправке сообщения в формате: 'Твой ответ: <ответ пользователя>' и добавила его к функциям в profiles и coliving
2) Убрала магические числа в константы.

2024-04-09 06:14 UTC, TomatoInOil requested changes

2024-04-09 06:14 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
>  async def start(
Давай не будем использовать этот декоратор там, где используется изменение сообщения [edit_text](https://docs.python-telegram-bot.org/en/stable/telegram.message.html#telegram.Message.edit_text), потому что в этом случае могут происходить вот такие странности 
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/3230f342-1997-4c32-807c-2470220d7ae0)
А ещё в этом случае нам не нужно оставлять ответ в диалоге. Но, например, для кнопок "Я парень" или "Я девшука" во время прохождения анкеты - это важно.

2024-04-09 06:14 UTC, TomatoInOil commented on src/bot/conversations/profile/handlers.py
> +                #  ),
Лишний комментарий

2024-04-09 06:14 UTC, TomatoInOil commented on src/bot/conversations/profile/templates.py
> +ERR_PHOTO_NOT_TEXT = f"Отправь до {PHOTO_MAX_NUMBER} фотографий для своего профиля."
Отлично

2024-04-09 23:44 UTC, TatianaBelova333 commented on src/bot/conversations/profile/callback_funcs.py
>  async def start(
Убрала из декоратора возможность отправки текста, введенного пользователем. Удалила декоратор из функций, где он не нужен (как на скриншоте выше).

2024-04-10 04:43 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
>  async def start(
В поиске соседа уже учтено, что нам нужно показать итоговый выбор пользователя, а также здесь сообщения редактируются, поэтому декоратор там не нужен
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/50723663-03bd-433d-bd6a-16a51a8edabf)
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/a26652fa-6408-433c-acaf-6f79d99e67db)

2024-04-10 16:13 UTC, TatianaBelova333 commented on src/bot/conversations/profile/callback_funcs.py
>  async def start(
Пока убрала декоратор из roomate_search.
Также вынесла тексты кнопок для коливинга в отдельный файл -  buttons.py.

Может заодно изменить  pattern=r"^is_visible:(True|False)$" ?

2024-04-11 09:47 UTC, TomatoInOil commented on src/bot/conversations/coliving/callback_funcs.py
Да, эта функция обрабатывает получение фотографий. Когда мы получаем фотографию, то мы сохраняем информацию о ней в контекст. Если фотографий было получено `templates.PHOTO_MAX_NUMBER`, то мы переходим к следующему шагу
```Python
state = await send_received_room_photos(update, context)
return state
```
А если нет, то остаёмся в том же state, в котором сейчас находимся. Возвращение None означает остаться в том же state, в котором находимся. 
>To change the state of conversation, the callback function of a handler must return the new state after responding to the user. If it does not return anything (returning [None](https://docs.python.org/3/library/constants.html#None) by default), the state will not change.
**Источник:** https://docs.python-telegram-bot.org/en/stable/telegram.ext.conversationhandler.html#conversationhandler

Конечно, можно было бы убрать эту строку, ведь это ничего бы не изменило, но разработчик, который это написал, скорее всего хотел явно указать, что мы остаёмся в том же состоянии.

2024-04-11 23:58 UTC, TatianaBelova333 commented
Убрала pattern=r"^is_visible:(True|False)$"

2024-04-12 08:48 UTC, TomatoInOil approved these changes

2024-04-12 08:48 UTC, merged