Feature/coliving transfer
Studio-Yandex-Practicum/coliving_bot pull request #142
Opened 2024-04-15 10:01 UTC by nalivastya

Функция по передаче коливинга.

2024-04-15 14:28 UTC, TomatoInOil requested changes

2024-04-15 14:28 UTC, TomatoInOil commented on src/bot/conversations/coliving/callback_funcs.py
> +    keyboard = InlineKeyboardMarkup.from_column(button_column=buttons)
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/4f33d34f-44de-4084-95c6-6d98a909cf29)
 
Не рассмотрен случай, если список пользователей пуст. Нужно отправлять тогда сообщение, в котором это говорится.

2024-04-15 14:28 UTC, TomatoInOil commented on src/bot/conversations/coliving/callback_funcs.py
> +    keyboard = InlineKeyboardMarkup.from_column(button_column=buttons)
Также нужно добавить пагинацию, если пользователей много, я думаю, что отображать по 6 будет хорошо.
Чтобы это выглядело наподобие: 
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/e374739b-b3f7-4ba7-990a-94e683869b1d)

2024-04-15 14:28 UTC, TomatoInOil commented on src/bot/conversations/coliving/callback_funcs.py
> +):
На эту функцию можно повесить декоратор 
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/873402454b4d6422d52bd702337706ac3daa9979/src/bot/conversations/common_functions/common_funcs.py#L15

2024-04-15 14:28 UTC, TomatoInOil commented on src/backend/profiles/api_views.py
> +    serializer_class = UserResidenceSerializer
Это представление нигде не используется.

2024-04-16 07:31 UTC, nalivastya commented on src/bot/conversations/coliving/callback_funcs.py
> +    keyboard = InlineKeyboardMarkup.from_column(button_column=buttons)
не понимаю как выводить вторую страницу. новым сообщением?

2024-04-16 10:20 UTC, nalivastya commented
Убрала лишний код. Добавила ответ на случай пустого списка пользователей. Добавила пагинацию и её обработку. Не придумала как сделать такие красивые кнопочки)))

2024-04-16 17:14 UTC, TomatoInOil requested changes

2024-04-16 17:14 UTC, TomatoInOil commented on src/backend/profiles/api_views.py
> +        return UserFromTelegram.objects.filter(residence_id=self.kwargs["pk"])
Опечатка ColivingRo`o`mmatesView

2024-04-16 17:14 UTC, TomatoInOil commented on src/backend/profiles/api_views.py
> +        return UserFromTelegram.objects.filter(residence_id=self.kwargs["pk"])
По логам
```SQL
<...>
2024 - 04 - 16 18 : 20 : 02, 574 - django.db.backends - DEBUG - (0.000) 
SELECT "profiles_profile"."id", <...> "profiles_profile"."age" FROM "profiles_profile" WHERE "profiles_profile"."user_id" = 73 LIMIT 21; args =(73,); alias = default

2024 - 04 - 16 18 : 20 : 02, 575 - django.db.backends - DEBUG - (0.000) 
SELECT "profiles_profile"."id", <...> "profiles_profile"."age" FROM "profiles_profile" WHERE "profiles_profile"."user_id" = 74 LIMIT 21; args =(74,); alias = default
<...>
```
На каждого пользователя запрашивается отдельно профиль, можно избежать этого, добавив `.select_related("user_profile")`: https://docs.djangoproject.com/en/5.0/ref/models/querysets/#select-related
У нас получится такой запрос
```SQL
SELECT 
  "profiles_userfromtelegram"."id", 
  "profiles_userfromtelegram"."telegram_id", 
  "profiles_userfromtelegram"."residence_id", 
  "profiles_profile"."id", 
  "profiles_profile"."location_id", 
  "profiles_profile"."about", 
  "profiles_profile"."is_visible", 
  "profiles_profile"."created_date", 
  "profiles_profile"."user_id", 
  "profiles_profile"."name", 
  "profiles_profile"."sex", 
  "profiles_profile"."age" 
FROM 
  "profiles_userfromtelegram" 
  LEFT OUTER JOIN "profiles_profile" ON (
    "profiles_userfromtelegram"."id" = "profiles_profile"."user_id"
  ) 
WHERE 
  "profiles_userfromtelegram"."residence_id" = 1 
ORDER BY 
  "profiles_userfromtelegram"."telegram_id" ASC
```
Но нам не нужны все поля профиля, можно использовать 
```Python
.values("user_profile__age", "user_profile__name", "telegram_id")
```
, исправив в сериализаторе src для полей 
```Python
age = serializers.IntegerField(source="user_profile__age")
name = serializers.CharField(source="user_profile__name")
```
Получится такой запрос
```SQL
SELECT 
  "profiles_profile"."age", 
  "profiles_profile"."name", 
  "profiles_userfromtelegram"."telegram_id" 
FROM 
  "profiles_userfromtelegram" 
  LEFT OUTER JOIN "profiles_profile" ON (
    "profiles_userfromtelegram"."id" = "profiles_profile"."user_id"
  ) 
WHERE 
  "profiles_userfromtelegram"."residence_id" = 1 
ORDER BY 
  "profiles_userfromtelegram"."telegram_id" ASC
```

2024-04-18 08:00 UTC, nalivastya commented on src/backend/profiles/api_views.py
> +        return UserFromTelegram.objects.filter(residence_id=self.kwargs["pk"])
Внесла изменения согласно замечаниям, добавила обработку отмены передачи коливинга, отправку сообщения новому владельцу коливинга + мелкий рефакторинг

2024-04-18 11:55 UTC, nalivastya commented on src/backend/profiles/api_views.py
> +        return UserFromTelegram.objects.filter(residence_id=self.kwargs["pk"])
> По логам
> 
> ```sql
> <...>
> 2024 - 04 - 16 18 : 20 : 02, 574 - django.db.backends - DEBUG - (0.000) 
> SELECT "profiles_profile"."id", <...> "profiles_profile"."age" FROM "profiles_profile" WHERE "profiles_profile"."user_id" = 73 LIMIT 21; args =(73,); alias = default
> 
> 2024 - 04 - 16 18 : 20 : 02, 575 - django.db.backends - DEBUG - (0.000) 
> SELECT "profiles_profile"."id", <...> "profiles_profile"."age" FROM "profiles_profile" WHERE "profiles_profile"."user_id" = 74 LIMIT 21; args =(74,); alias = default
> <...>
> ```
> 
> На каждого пользователя запрашивается отдельно профиль, можно избежать этого, добавив `.select_related("user_profile")`: https://docs.djangoproject.com/en/5.0/ref/models/querysets/#select-related У нас получится такой запрос
> 
> ```sql
> SELECT 
>   "profiles_userfromtelegram"."id", 
>   "profiles_userfromtelegram"."telegram_id", 
>   "profiles_userfromtelegram"."residence_id", 
>   "profiles_profile"."id", 
>   "profiles_profile"."location_id", 
>   "profiles_profile"."about", 
>   "profiles_profile"."is_visible", 
>   "profiles_profile"."created_date", 
>   "profiles_profile"."user_id", 
>   "profiles_profile"."name", 
>   "profiles_profile"."sex", 
>   "profiles_profile"."age" 
> FROM 
>   "profiles_userfromtelegram" 
>   LEFT OUTER JOIN "profiles_profile" ON (
>     "profiles_userfromtelegram"."id" = "profiles_profile"."user_id"
>   ) 
> WHERE 
>   "profiles_userfromtelegram"."residence_id" = 1 
> ORDER BY 
>   "profiles_userfromtelegram"."telegram_id" ASC
> ```
> 
> Но нам не нужны все поля профиля, можно использовать
> 
> ```python
> .values("user_profile__age", "user_profile__name", "telegram_id")
> ```
> 
> , исправив в сериализаторе src для полей
> 
> ```python
> age = serializers.IntegerField(source="user_profile__age")
> name = serializers.CharField(source="user_profile__name")
> ```
> 
> Получится такой запрос
> 
> ```sql
> SELECT 
>   "profiles_profile"."age", 
>   "profiles_profile"."name", 
>   "profiles_userfromtelegram"."telegram_id" 
> FROM 
>   "profiles_userfromtelegram" 
>   LEFT OUTER JOIN "profiles_profile" ON (
>     "profiles_userfromtelegram"."id" = "profiles_profile"."user_id"
>   ) 
> WHERE 
>   "profiles_userfromtelegram"."residence_id" = 1 
> ORDER BY 
>   "profiles_userfromtelegram"."telegram_id" ASC
> ```

вроде получилось

2024-04-18 12:34 UTC, TomatoInOil approved these changes

2024-04-18 12:35 UTC, merged