Deleted  bttns, replaced them with  bttns & added user-profile  bttn
Studio-Yandex-Practicum/coliving_bot pull request #149
Opened 2024-04-19 12:07 UTC by StriderDunedain

2024-04-20 09:49 UTC, TomatoInOil requested changes

2024-04-20 09:49 UTC, TomatoInOil commented on .env.example
Нужно вернуть этот файл обратно, находясь в корневой директории проекта и в этой ветке, выполни 
```bash
git checkout origin/develop -- .env.example
```

2024-04-20 09:49 UTC, TomatoInOil commented on src/bot/conversations/profile/handlers.py
> +            # ),
Лишний комментарий

2024-04-20 09:49 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +    context.user_data["profile_info"] = name
Сломалось изменение имени

2024-04-20 12:44 UTC, ArtemKAF commented on src/bot/conversations/profile/callback_funcs.py
> +    context.user_data["profile_info"] = name
В меню коливинга кнопка "Удалить коливинг" есть вне редактирования анкеты и внутри редактирования анкеты. Бот прямо навязывает удалить коливинг.
В меню редактирования анкеты коливинга нет кнопки "вернуться" как в диалоге редактирования профиля.

2024-04-20 13:11 UTC, StriderDunedain commented on src/bot/conversations/profile/callback_funcs.py
> +    context.user_data["profile_info"] = name
Спасибо, уберу как доберусь до компа!

2024-04-20 21:13 UTC, StriderDunedain commented on src/bot/conversations/profile/callback_funcs.py
> +    context.user_data["profile_info"] = name
Все починил, спасибо за комменты!

2024-04-21 11:54 UTC, TomatoInOil approved these changes

2024-04-21 11:56 UTC, merged