Feature/logger
Studio-Yandex-Practicum/coliving_bot pull request #15
Opened 2023-12-12 21:05 UTC by NechepurenkoA

Добавил логгер в проект, настроил его в файле конфигураций `config.py`.
Добавил в `.gitignore` папку для логов.

2023-12-12 21:09 UTC, NechepurenkoA commented
Папка `.data` будет находится по пути `./src/.data`, если надо - поменяю.

2023-12-13 05:45 UTC, TomatoInOil requested changes

2023-12-13 05:45 UTC, TomatoInOil commented on src/bot/utils/config.py
> +logging.basicConfig(level=logging.DEBUG, format=LOG_FORMAT)
Хорошо будет добавить возможность изменять уровень логирования в переменных окружения 
Пригодится https://docs.python.org/3/library/logging.html#logging.getLevelName

2023-12-13 05:45 UTC, TomatoInOil commented on src/bot/utils/logger.py
> +    when='midnight',
Т. к. будут ещё логи Django, то лучше назвать файл так, чтобы было понятно откуда пишутся логи, а ещё обычно логи сохраняют в расширении `.log` , т.е. `bot.log`

2023-12-13 05:45 UTC, TomatoInOil commented on src/bot/utils/logger.py
> +logging.getLogger('httpx').setLevel(logging.WARNING)
Т.к. этот файл нигде не импортируется, то этот код не выполняется, следовательно `httpx` имеет уровень логирования тот же, что выставлен в `logging.basicConfig` в файле `config.py`
Можно сделать отдельную функцию, которая применяет настройки логирования и запускать её в `run_bot.py` перед `create_bot_app`
Пример:
https://github.com/Studio-Yandex-Practicum/you_can_bot/blob/55226035b6e2d43d0501f1b8453a4ab8ce011484/src/bot/utils/logger.py#L17-L39

2023-12-13 06:56 UTC, NechepurenkoA commented on src/bot/utils/logger.py
> +    when='midnight',
Перекинул все магические числа и пути в `.config` сделав их константами.

2023-12-13 07:28 UTC, TomatoInOil commented on src/bot/bot.py
Я имел в виду в run_bot, чтобы явно отслеживалось, что происходит при запуске бота 
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/52083852c2c33fe260d4763b78adad879719f93c/src/bot/run_bot.py#L6-L8
Перед вызовом create_bot_app()

2023-12-13 07:49 UTC, NechepurenkoA commented on src/bot/bot.py
Сглупил :) Я что-то так сначала сделал, а потом потерялся и вообще куда-то не туда засунул видимо.

2023-12-13 07:52 UTC, therealestbatiskaf commented
А почему isort `utils` закидывает к библиотекам, если это импорт из локальных и он должен быть внизу? (это после pre-commit'а произошло, если что)

2023-12-13 13:56 UTC, TomatoInOil commented
> А почему isort `utils` закидывает к библиотекам, если это импорт из локальных и он должен быть внизу? (это после pre-commit'а произошло, если что)

Это упущение в настройке, нужно добавить 
```
src_paths = ["src/bot", "src/backend"]
```
Вот сюда 
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/f4a922fc0319aa9d72ce607b8902e29915ad0538/pyproject.toml#L28-L30

2023-12-13 14:29 UTC, TomatoInOil approved these changes

2023-12-13 14:29 UTC, merged