Добавил функционал жалоб
Studio-Yandex-Practicum/coliving_bot pull request #178
Opened 2024-06-12 12:41 UTC by StDemidov

Реализовал функционал жалоб пока только на пользователей
- Реализовал возможность прикрепления скриншотов
- Поменял dataclass Report + enum Categories (добавил поле скриншота и поменял категории)
- Пока не создавал в конце запрос к апи на создание жалобы

2024-06-22 11:43 UTC, TomatoInOil requested changes
Супер! Есть несколько небольших моментов, которые можно улучшить.

2024-06-22 11:43 UTC, TomatoInOil commented on src/bot/conversations/complain/callback_funcs.py
> +        )
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/9ef185d6-f2d7-4451-8bf6-d4f0399d0986)

Т.к. кнопка "Нет, у меня нет скриншота" - это inline кнопка, то ReplyKeyboardRemove() не работает в этом случае. В этом случае можно использовать 
```Python
# Заменит текст сообщения, к которому была прикреплена нажатая кнопка, клавиатура удалится
update.effective_message.edit_text(text=message_text)
```
Или использовать декоратор 
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/7bc34fa485d459a4238e72b3730bd0d01d6d5220/src/bot/conversations/common_functions/common_funcs.py#L16-L20
Который вместе с отправкой пользователю сообщения с текстом нажатой кнопки удалит клавиатуру
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/7bc34fa485d459a4238e72b3730bd0d01d6d5220/src/bot/conversations/common_functions/common_funcs.py#L25

2024-06-22 11:43 UTC, TomatoInOil commented on src/bot/conversations/complain/callback_funcs.py
> +        )
Тоже самое можно сказать про 
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/6f332ac665f44b52d02d9776735eee1d6e8cbb71/src/bot/conversations/complain/callback_funcs.py#L96-L103

2024-06-22 11:43 UTC, TomatoInOil commented on src/bot/conversations/complain/handlers.py
> +        ),
Также здесь тоже остаётся клавиатура
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/b99eb141-ce4d-4ea9-8845-edd7bd438234)

Можно попробовать повесить на эту функцию декоратор, но конкретно для этого хендлера, а не для всех случаев её использования 
```Python
common_funcs.add_response_prefix()(common_funcs.cancel)
```

2024-06-22 11:43 UTC, TomatoInOil commented on src/bot/conversations/complain/keyboards.py
> +    category_keyboard = InlineKeyboardMarkup.from_column(
Т.к. клавиатура не зависит от входных данных функции, то можно её оформить просто как константу.

2024-06-22 11:43 UTC, TomatoInOil commented on src/bot/conversations/complain/keyboards.py
> +    category_keyboard = InlineKeyboardMarkup.from_column(
И здесь
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/6f332ac665f44b52d02d9776735eee1d6e8cbb71/src/bot/conversations/complain/keyboards.py#L31-L32

2024-06-22 11:43 UTC, TomatoInOil commented on src/bot/internal_requests/entities.py
> +    CATEGORY_OTHER = "Другое"
Можно использовать для кнопок вместо этих констант, чтобы это знание не повторялось в двух местах
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/6f332ac665f44b52d02d9776735eee1d6e8cbb71/src/bot/conversations/complain/buttons.py#L9-L14

Более того по ним можно итерироваться и сократить определение клавиатуры
```Python
InlineKeyboardMarkup.from_column(
        button_column=[
            InlineKeyboardButton(text=category, callback_data=category)
            for category in Categories
        ]
    )
```

2024-06-22 11:43 UTC, TomatoInOil commented on src/bot/conversations/complain/callback_funcs.py
> +    return states.RESULT
Т.к. мы ожидаем только 1 скриншот, то можно пропустить шаг нажатия кнопки "Сохранить фото", а сразу в этой функции продолжить логикой функции final_report для случая с изображением
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/6f332ac665f44b52d02d9776735eee1d6e8cbb71/src/bot/conversations/complain/callback_funcs.py#L118-L129
То есть диалог будет выглядеть 

> **Бот:** Есть ли у вас скриншот, на котором демонстрируется нарушение?
**Пользователь:** Нажимает кнопку "Да, я хотел бы прикрепить скриншот"
**Бот:** Отлично, скриншот поможет установить нарушение! Отправь скриншот.
**Пользователь:** Отправляет фото
**Бот:** Ваша жалоба сформирована! <...>

Тогда можно будет убрать конструкцию if в самом final_report оставив только логику, нужную для отправки сообщения без текста

2024-06-26 14:14 UTC, NRenat commented on src/backend/search/views.py
> +                {"detail": ALREADY_REPORTED}, status=status.HTTP_208_ALREADY_REPORTED
Не знаю насколько статус 208 подходит к этому случаю, исключая название, конечно же.
По дефолту возвращается код 400 (пара reporter-reported_user уже существует в БД), и бот падает из-за response.raise_for_status() в _post_request(). У меня не получалось вытащить причину (json ответ вместе со статусом) для обработки, поэтому возвращаю статус код 20х, который raise_for_status() пропускает.

2024-06-26 14:17 UTC, NRenat commented on src/backend/search/views.py
> +            reporter=reporter, reported_user=reported_user
Не знаю насколько статус 208 подходит к этому случаю, исключая название, конечно же.
По дефолту возвращается код 400 (пара reporter-reported_user уже существует в БД), и бот падает из-за response.raise_for_status() в _post_request(). У меня не получалось вытащить причину (json ответ вместе со статусом) для обработки, поэтому возвращаю статус код 20х, который raise_for_status() пропускает.

2024-06-26 14:29 UTC, NRenat commented on src/backend/search/views.py
> +                {"detail": ALREADY_REPORTED}, status=status.HTTP_208_ALREADY_REPORTED
Не знаю насколько статус 208 подходит к этому случаю, исключая название, конечно же.
По дефолту возвращается код 400 (пара reporter-reported_user уже существует в БД), и бот падает из-за response.raise_for_status() в _post_request(). У меня не получалось вытащить причину (json ответ вместе со статусом) для обработки, поэтому возвращаю статус код 20х, который raise_for_status() пропускает.

2024-06-27 15:10 UTC, TomatoInOil requested changes

2024-06-27 15:10 UTC, TomatoInOil commented on src/backend/coliving_bot/urls.py
> +
https://docs.djangoproject.com/en/5.0/topics/settings/#using-settings-in-python-code

2024-06-27 15:10 UTC, TomatoInOil commented on src/bot/conversations/complain/callback_funcs.py
> +    )
Давай добавим сюда кнопку "Пропустить", если категория не равна "Другое", чтобы комментарий был необязателен в этом случае.

2024-06-28 14:11 UTC, TomatoInOil approved these changes

2024-06-28 14:11 UTC, merged