Feature/error handler
Studio-Yandex-Practicum/coliving_bot pull request #18
Opened 2023-12-13 19:16 UTC by NechepurenkoA

Сделал "ловца" ошибок. 

Сообщение пока от руки написал, пробное, жду совета как сделать лучше.

Всё проверял - работает, в логи выводится `traceback` в сообщения пользователю прилетает лишь ошибка. 

Для проверки создавал комманду, как показано в примере.

2023-12-13 19:28 UTC, NechepurenkoA commented
Я не совсем понял о логировании контекста, мне надо прям объект `context` прям передать в логи или все и так ок?

2023-12-22 09:15 UTC, TomatoInOil requested changes

2023-12-22 09:15 UTC, TomatoInOil commented on src/bot/run_bot.py
> +    application.add_error_handler(error_handler)
Давай перенесём добавление хендлера внутрь функции `create_bot_app()`, она для этого и задумывалась

2023-12-22 09:15 UTC, TomatoInOil commented on src/bot/error_handler/callback_funcs.py
> +    logger.error("Exception while handling an update:", exc_info=context.error)
Здесь происходит дублирование логов, исправляется заменой `"logger"` на `__name__`, также можно вынести `getLogger` в константы
```python
_LOGGER = logging.getLogger(__name__)
```

2023-12-22 09:15 UTC, TomatoInOil commented on src/bot/error_handler/callback_funcs.py
> +    logger.error("Exception while handling an update:", exc_info=context.error)
Можно добавить вывод контекста
```Python
error_text = (
    "Exception while handling an update:"
    f"\ncontext.user_data={context.user_data}"
    f"\ncontext.chat_data={context.chat_data}"
)
```

2023-12-22 09:15 UTC, TomatoInOil commented on src/bot/error_handler/callback_funcs.py
> +    )
Здесь могут возникнуть исключения `KeyError`, чтобы этого избежать, можно сначала проверить, что обновление соответствует классу `Update`
```Python
if isinstance(update, Update):
```
В случае `True` можно будет отправить сообщение через shortcut
```python
await update.effective_chat.send_message(
    text=message, parse_mode=ParseMode.HTML
)
```
https://docs.python-telegram-bot.org/en/stable/telegram.chat.html#telegram.Chat.send_message

2023-12-24 18:57 UTC, TomatoInOil approved these changes

2023-12-24 18:57 UTC, merged