Add age range notification mod. [D-1 - task 184]
Studio-Yandex-Practicum/coliving_bot pull request #189
Opened 2024-06-25 17:36 UTC by ilililililililililililililil

2024-06-25 19:45 UTC, ilililililililililililililil commented
Done

2024-06-27 14:19 UTC, TomatoInOil requested changes

2024-06-27 14:19 UTC, TomatoInOil commented on src/bot/conversations/profile/templates.py
> +AGE_ERROR_MSG_STATIC = "Можно ввести возраст от 18 до 99 лет."
Если подставить минимальный и максимальный возраст сразу в строку в этом месте, то останется только одно сообщение
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/386529702ccb376046797914b7c7ebb347df294b/src/bot/conversations/profile/constants.py#L1-L2
https://docs.python.org/3/tutorial/inputoutput.html#tut-f-strings

2024-06-27 14:56 UTC, ilililililililililililililil commented on src/bot/conversations/profile/templates.py
> +AGE_ERROR_MSG_STATIC = "Можно ввести возраст от 18 до 99 лет."
не было цели сократить кол-во констант. В коде используется 1 статичное и 1 динамическое, если есть возможность использовать динамические границы, почему их не оставить?

2024-06-27 15:10 UTC, ilililililililililililililil commented on src/bot/conversations/profile/templates.py
> +AGE_ERROR_MSG_STATIC = "Можно ввести возраст от 18 до 99 лет."
Если всех устроит статичное одинаковое сообщение - ок

2024-06-27 15:16 UTC, TomatoInOil commented on src/bot/conversations/profile/templates.py
> +AGE_ERR_MSG = "Можно ввести возраст от 18 до 99 лет."
Я предлагаю использовать f-строку, подставляя прямо здесь константы. 
Если разработчик изменит, например, константу MIN_AGE на 16, то сообщение будет отправляться с актуальными границами. В этом смысл моего предыдущего комментария.
https://docs.python.org/3/tutorial/inputoutput.html#tut-f-strings

2024-06-27 15:19 UTC, ilililililililililililililil commented on src/bot/conversations/profile/templates.py
> +AGE_ERR_MSG = "Можно ввести возраст от 18 до 99 лет."
а, я думал ты предлагаешь к статике перейти, ок

2024-06-27 15:31 UTC, TomatoInOil approved these changes

2024-06-27 15:39 UTC, merged