Add hyphen exists check  [task 185]
Studio-Yandex-Practicum/coliving_bot pull request #190
Opened 2024-06-25 19:41 UTC by ilililililililililililililil

2024-06-25 19:45 UTC, ilililililililililililililil commented
Done

2024-06-27 14:29 UTC, TomatoInOil requested changes

2024-06-27 14:29 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +    if len(name) > 0 and bool(set(alphabet).intersection(set(name.lower()))):
Регулярное выражение ограничивает допустимые символы,
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/386529702ccb376046797914b7c7ebb347df294b/src/bot/conversations/profile/constants.py#L11
 если текстовое сообщение не попадает под регулярное выражение, то вызывается `handle_wrong_name`
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/386529702ccb376046797914b7c7ebb347df294b/src/bot/conversations/profile/handlers.py#L75-L77
Поэтому эта проверка избыточна

2024-06-27 14:29 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +            name = name[:-1:]
Это можно сделать проще
https://docs.python.org/3/library/stdtypes.html#str.strip

2024-06-27 14:57 UTC, ilililililililililililililil commented on src/bot/conversations/profile/callback_funcs.py
> +    if len(name) > 0 and bool(set(alphabet).intersection(set(name.lower()))):
проверка не избыточна, она обыгрывает случай, если на вход подается без букв - только дефисы, если есть хоть 1 символ - дефисы ниже будут убраны и не упадет на while по индексу

2024-06-27 15:05 UTC, ilililililililililililililil commented on src/bot/conversations/profile/callback_funcs.py
> +            name = name[:-1:]
в случае использования этого, остальное можно не делать, да. все эти движения были из-за  while

2024-06-27 15:05 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +    if len(name) > 0 and bool(set(alphabet).intersection(set(name.lower()))):
> проверка не избыточна, она обыгрывает случай, если на вход подается без букв - только дефисы, если есть хоть 1 символ - дефисы ниже будут убраны и не упадет на while по индексу

Согласен. Но если ты согласишься, что использовать `.strip("-")` будет проще, то после его применения будет достаточно проверить, что строка не пустая

2024-06-27 15:08 UTC, ilililililililililililililil commented
@TomatoInOil напиши, если можно мерджить

2024-06-27 15:18 UTC, TomatoInOil approved these changes

2024-06-27 15:19 UTC, TomatoInOil commented
> @TomatoInOil напиши, если можно мерджить

Можно

2024-06-27 15:20 UTC, ilililililililililililililil commented
добавил вызов handle_wrong_name(update=update), если имя пустое после strip

2024-06-27 15:31 UTC, merged

2024-06-27 15:41 UTC, ilililililililililililililil commented on src/bot/conversations/profile/callback_funcs.py
> +    if len(name) > 0 and bool(set(alphabet).intersection(set(name.lower()))):
strip - хорошо, я мало со строками имею дело, не знал о нем