Добавлена блокировка пользователя администратором
Studio-Yandex-Practicum/coliving_bot pull request #196
Opened 2024-07-01 15:06 UTC by NRenat

- Добавлено скрытие профиля пользователя и профиля его коливинга в боте, если пользователь был заблокирован.
- В жалобы добавлены кнопки "Принять", "Отклонить", которые автоматически блокируют пользователя/меняют статус жалобы/скрывают его профиля в боте.
- Добавлено ограничение доступа к боту, если пользователь заблокирован.
- Изменен шаблон preview для лучшей читабельности.

2024-07-04 06:14 UTC, TomatoInOil requested changes
Заблокированному пользователю не имеет смысла отправлять рассылку, поэтому можно сюда добавить filter
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/b4641d22f834c9bdbfa1a9e43508f502f820f914/src/backend/mailing/api_views.py#L34

2024-07-04 06:14 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +            return ConversationHandler.END
Т.к. здесь ты уже получаешь профиль, то можно сразу проверить, что пользователь забанен без check_user_ban, где совершается ещё один запрос на получение профиля. 
```Python
if context.user_data["profile_info"].is_banned:
```

2024-07-04 06:14 UTC, TomatoInOil commented on src/bot/conversations/roommate_search/callback_funcs.py
> +        return ConversationHandler.END
В функциях `start()` из 
- `src/bot/conversations/roommate_search/callback_funcs.py`
- `src/bot/conversations/coliving_search/callback_funcs.py`
- `src/bot/conversations/coliving/callback_funcs.py`

Есть 2 общих момента: 
1. Эта логика проверки, что пользователь не забанен 
2. Декоратор `@profile_required`

Можно перенести эту логику в декоратор `profile_required`, чтобы не совершать ещё один запрос к API на получение профиля

Есть ещё один случай использования `@profile_required`
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/386529702ccb376046797914b7c7ebb347df294b/src/bot/conversations/invitation/callback_funcs.py#L14-L20
Но я думаю, что проверка, что пользователь не в бане не помешает здесь

2024-07-04 06:14 UTC, TomatoInOil commented on src/backend/profiles/admin.py
>      )
Сюда можно ещё добавить Inline отображение для коливингов пользователя, чтобы админу не искать их. 
https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#inlinemodeladmin-objects

2024-07-04 06:14 UTC, TomatoInOil commented on src/backend/profiles/admin.py
> +                coliving.save()
Чтобы у других пользователей не было проблем со взаимодействием с этим пользователем, давай удалим лайки, связанные с ним
```Python
ProfileLike.objects.filter(Q(sender=profile) | Q(receiver=profile))
ColivingLike.objects.filter(Q(sender=profile) | Q(coliving=coliving))
```
, а также установим `obj.residence` в `None`

2024-07-05 19:24 UTC, NRenat commented on src/backend/profiles/admin.py
>      )
Вместо Inline реализовал ссылку на коливинг.

2024-07-08 13:20 UTC, TomatoInOil approved these changes

2024-07-08 13:20 UTC, merged