Добавлено отображение никнейма в сообщение о взаимном лайке
Studio-Yandex-Practicum/coliving_bot pull request #198
Opened 2024-07-02 22:06 UTC by NRenat

- Также добавлена возможность перейти к переписке с пользователями, у которых не был установлен никнейм в телегаме.

2024-07-02 22:11 UTC, NRenat commented
Тестил отображение никнейма на новом тг акке, где не настраивал никнейм. Бот вел к нему через @None. 
ps "@" перенес из шаблона в функцию, чтобы для пользователей без никнейма "@" так же подсвечивалась бы, хотя там она не функциональна.

2024-07-03 17:36 UTC, TomatoInOil requested changes

2024-07-03 17:36 UTC, TomatoInOil commented on src/bot/conversations/match_requests/utils.py
> +        like_sender_username = f'<a href="tg://user?id={sender_id}">@{user.name}</a>'
Предлагаю эту логику поместить в функцию `_get_tg_username`, немного её переименовав, это избавит от дублирования и улучшит читаемость кода 
```Python
async def _get_username_or_profile_link(
    context: ContextTypes.DEFAULT_TYPE, telegram_id: int
) -> str:
    chat = await context.bot.get_chat(chat_id=telegram_id)
    if chat.username:
        return f"@{chat.username}"
    if chat.first_name:  # Можно взять имя из Telegram, если оно есть
        return f'<a href="tg://user?id={telegram_id}">@{chat.first_name}</a>'
    profile = await api_service.get_user_profile_by_telegram_id(telegram_id=telegram_id)
    return f'<a href="tg://user?id={telegram_id}">@{profile.name}</a>'
```

2024-07-03 17:38 UTC, TomatoInOil commented on src/bot/conversations/match_requests/utils.py
> +        like_sender_username = f'<a href="tg://user?id={sender_id}">@{user.name}</a>'
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/0883e2ddec3f8429df8a40236115320a74c21074/src/bot/conversations/match_requests/utils.py#L26

2024-07-03 18:51 UTC, TomatoInOil approved these changes

2024-07-03 18:51 UTC, merged