Feature/creating django models
Studio-Yandex-Practicum/coliving_bot pull request #20
Opened 2023-12-16 09:01 UTC by bbv-87

Удалено приложение 'api'
Созданы приложения 'search', 'images', 'profiles'
Описаны модели по схеме, добавлены ограничения для моделей, добавлены миграции
Создана админ панель для тестирования

2023-12-19 08:59 UTC, TomatoInOil requested changes
Супер, ты отлично проработал модели, есть, что поправить, но не очень много.

2023-12-19 08:59 UTC, TomatoInOil commented on pyproject.toml
> +pillow = "^10.1.0"
Это пригодится и на проде. 
```
poetry remove pillow --group dev
```
```
poetry add pillow
```

2023-12-19 08:59 UTC, TomatoInOil commented on src/backend/images/models.py
> +    )
Мне нужно было пояснить этот момент подробнее, здесь имеется в виду `file_id` из Telegram, который можно использовать для повторной отправки изображения, соответственно, оно может быть пустым, если изображение ещё не было ни разу отправлено
https://docs.python-telegram-bot.org/en/stable/telegram.file.html#telegram.File.file_id
https://core.telegram.org/bots/api#sending-files
`file_id` из себя представляет просто длинную строку, например, `AgADBAADZRAxGyhM3FKSE4qKa-RODckQHxsoABDHe0BDC1GzpGACAAEC`

2023-12-19 08:59 UTC, TomatoInOil commented on src/backend/profiles/constants.py
> +    SPB = ("Санкт-Петербург", "Санкт-Петербург")
Чтобы было проще потом добавить другие города, можно не зашивать это в код, сделать так, чтобы через админку можно было добавить ещё города, а Москву и Санкт-Петербург вынести в фикстуры.

2023-12-19 08:59 UTC, TomatoInOil commented on src/backend/profiles/constants.py
> +    WOMAN = ("Девушка", "Девушка")
Поле в `Profile` называется `sex`, а здесь в имени класса используется `Gender`, давай использовать одно слово для согласованности

2023-12-19 08:59 UTC, TomatoInOil commented on src/backend/profiles/models.py
> +    )
[Positive**Big**IntegerField](https://docs.djangoproject.com/en/5.0/ref/models/fields/#positivebigintegerfield)
> User.id: ...But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.

https://core.telegram.org/bots/api#user

2023-12-19 08:59 UTC, TomatoInOil commented on src/backend/profiles/models.py
> +    )
Думаю, что здесь имеет смысл использовать `models.PROTECT`, т.к. анкеты пользователей и коливингов довольно важны, и мы бы не хотели их потерять просто при удалении какого-то Location по каким-то причинам

2023-12-19 08:59 UTC, TomatoInOil commented on src/backend/profiles/constants.py
> +    ABOUT_TEST_MAX = 1000
Думаю, что не имеет смысла ограничивать именно этот текст, т. к. в самом Telegram есть ограничение на кол-во символов в сообщении - это 4096 символов

2023-12-19 08:59 UTC, TomatoInOil commented on src/backend/search/models.py
> +            ),
Круто, что ты это продумал

2023-12-19 08:59 UTC, TomatoInOil commented on src/backend/images/models.py
> +        upload_to="images/",
Можно организовать древовидную структуру для оптимизации хранения изображений 
```
images/
├─ colivings/
│  ├─ 1/ # pk
│  │  ├─ filename.jpg
│  │  ├─ filename.jpg
│  ├─ 2/
│  │  ├─ filename.jpg
├─ profiles/
│  ├─ 1/
│  │  ├─ filename.jpg

```
Это можно сделать с помощью функций

https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.FileField.upload_to

2023-12-19 14:29 UTC, bbv-87 commented on src/backend/profiles/constants.py
> +    SPB = ("Санкт-Петербург", "Санкт-Петербург")
Понял, выполнено
Добавил фикстуры в проект и management команду для их загрузки

2023-12-19 14:31 UTC, bbv-87 commented on src/backend/profiles/models.py
> +    )
сори упустил из виду((

2023-12-19 16:00 UTC, bbv-87 commented
Выполнил исправления ошибок
Добавил management команду для загрузки фикстур и сам файл с фикстурами локаций
Обновил миграции

2023-12-20 08:40 UTC, TomatoInOil approved these changes

2023-12-20 08:58 UTC, merged