Создал ветку Profile для бота.
Studio-Yandex-Practicum/coliving_bot pull request #21
Opened 2023-12-17 11:58 UTC by Dadyx85

Даниил, приветствую. Описание проделанной работы:
1. Создал файлы констант: сообщений, кнопок, клавиатур, шагов бота.
2. Прописал необходимые хендлеры для всех шагов. Постарался учесть все ошибки. 
3. Прописал все нужные функции для обработки сообщений и коллбэков.
4. С сохранением в базу пока не занимался, так как базы нет.
5. С фотографиями сделал так: бот сначала ее загружает  по такому пути files/{update._effective_chat.id}/photos'.
Затем кодирует в Base64 и присваивает контексту. А когда надо посмотреть профиль для подтверждения, то загружает фото с указанного пути. В связи с этим в .gitignore прописал директорию /files.
Там в функции start прописан флаг для проверки, есть ли профиль. Сейчас он True - правая ветка. Для левой ветки надо сделать false.
Чтобы запустить на проверку, нужно в run_bot добавить хендлер profile.
P.S. Вроде всё проверил)))

2023-12-18 20:15 UTC, ArtemKAF commented on src/bot/conversations/profile/callback_funcs.py
> +    try:
Весь блок проверки введенного возраста лучше выполнить в виде валидатора, чтобы соблюсти принцип DRY. Не только в этом участке кода будет необходимо проверять, что пользователь ввел корректное числовое значение.

2023-12-19 19:55 UTC, Dadyx85 commented on src/bot/conversations/profile/callback_funcs.py
> +    try:
Создал validators.py. Он осуществляет проверку целочисленных значений. Вызываю его при проверки возраста, длины имени и максимального количества символов в описании о себе.

2023-12-20 19:43 UTC, Dadyx85 commented
Переместил валидатор в директорию src/bot/general. Исправил указанные недочеты.

2023-12-21 16:18 UTC, TomatoInOil requested changes

2023-12-21 16:18 UTC, TomatoInOil commented on src/bot/conversations/profile/handler.py
> +    entry_points=[CommandHandler(command="profile", callback=start)],
Необходимо добавить этот `handler` после создания `application` вот здесь:
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/7bfbf70706c3f491929b4b0f5e86bcb55c192922/src/bot/bot.py#L6-L8
https://docs.python-telegram-bot.org/en/stable/telegram.ext.application.html#telegram.ext.Application.add_handler

2023-12-21 16:18 UTC, TomatoInOil commented on src/bot/conversations/profile/template.py
> +)
Опечатка: 
> целым числом **в от** {min}

2023-12-21 16:18 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +        )
> Видимость анкеты: False

Как-то не по-человечески

2023-12-21 16:18 UTC, TomatoInOil commented on src/bot/conversations/profile/template.py
> +
Не поддерживает двойные имена
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/b277b229-f747-4321-9233-80a88deb5d14)
Также в паттерне можно использовать raw строку, то есть
`r"^[А-Яа-яA-Za-z\s]+$"`
Чтобы не было необходимости экранировать косую черту

2023-12-21 16:18 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +        return States.EDIT
Необходимость в этой конструкции возникла из-за того, что обновления разного типа обрабатываются в одной функции. 
Можно вынести случай, когда пользователь вместо кнопки пишет текстовое сообщение, в отдельную функцию. Тогда необходимость в этой конструкции исчезнет.
```python
# Новая функция для обработки этого случая
async def handle_text_input_instead_of_choosing_button(
    update: Update, context: ContextTypes.DEFAULT_TYPE
) -> int:
    await update.effective_message.reply_text(
        BUTTON_ERROR_MSG,
    )
```
И здесь заменить функцию handle_edit на handle_text_input_instead_of_choosing_button
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/368898a3c059762840f109f8f271a11c5c7b54e0/src/bot/conversations/profile/handler.py#L127

Так можно проделать везде, где ты использовал подобную конструкцию. Обрати внимание на то, что здесь функция ничего не возвращает 
> If it does not return anything (returning [None](https://docs.python.org/3/library/constants.html#None) by default), the state will not change.

https://docs.python-telegram-bot.org/en/latest/telegram.ext.conversationhandler.html#conversationhandler
А это означает, что её можно использовать в любом state и он не будет меняться после её выполнения, что избавляет от дублирования кода.

2023-12-21 16:18 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +        return States.EDIT_PHOTO
Ты можешь избежать использования конструкций `if`, обрабатывая разные кнопки разными функциями 
Пример:
```Python
States.EDIT: [
    CallbackQueryHandler(
        callback=start_filling_again, pattern=rf"^{FILL_AGAIN_BUTTON}"
    ),
    CallbackQueryHandler(
        callback=send_question_to_edit_about_myself, pattern=rf"^{ABOUT_BUTTON}"
    ),
    ...
]
```
```Python
async def start_filling_again(update: Update, _context: ContextTypes.DEFAULT_TYPE) -> int:
    await _send_chosen_choice_and_remove_buttons(update=update)
    await update.effective_message.reply_text(
        text=ASK_AGE_AGAIN,
    )
    return States.AGE


async def send_question_to_edit_about_myself(update: Update, context: ContextTypes.DEFAULT_TYPE) -> int:
    await _send_chosen_choice_and_remove_buttons(update=update)
    await update.effective_message.reply_text(
        text=ASK_ABOUT,
    )
    return States.EDIT_ABOUT_YOURSELF


async def _send_chosen_choice_and_remove_buttons(update: Update) -> None:
    callback_query = update.callback_query
    choice_text = callback_query.data
    await callback_query.message.edit_reply_markup()
    await callback_query.message.reply_text(text=choice_text)
```

Это упростит функции, они будут легче читаться

2023-12-21 16:18 UTC, TomatoInOil commented on src/bot/conversations/profile/handler.py
> +            ),
А в таких случаях, когда на обработку выбор не влияет, можно использовать `| (or)` в регулярном выражении
```python
CallbackQueryHandler(
    callback=handle_sex, pattern=rf"^({MALE_BUTTON}|{FEMALE_BUTTON})$"
),
```

2023-12-22 13:22 UTC, Dadyx85 commented
Исправил все указанные недочеты.

2023-12-23 05:28 UTC, ArtemKAF commented on src/bot/conversations/profile/callback_funcs.py
> +    user = update.message.from_user
В этом хэндреле вместо того, чтобы скачивать изображение на диск(без дополнительных манипуляций для удаления этого файла после использования диск переполнится рано или поздно), можно скачать его в память и кодировать из памяти:

    buffer = BytesIO()
    writer = BufferedWriter(buffer)
    await photo.download_to_memory(buffer)
    return base64.b64encode(buffer.getvalue())

Как такой подход отразиться на используемой оперативной памяти не знаю (нужно тестировать), но это должно работать быстрее, чем через сохранение на диск и избавит от необходимости "подчищать" временные файлы изображений.
P.S.: Для передачи впоследствии изображения из контекста достаточно заменить строку

`photo=(f"files/{chat_id}/photos/{update.message.from_user.full_name}_photo.jpg"),`

в хэндлере look_at_profile на

`photo=(base64.b64decode(context.user_data.get(IMAGE_FIELD))),`

2023-12-23 18:30 UTC, Dadyx85 commented on src/bot/conversations/profile/callback_funcs.py
> +    user = update.message.from_user
Исполнено.

2023-12-25 15:32 UTC, TomatoInOil approved these changes

2023-12-25 15:32 UTC, merged