added sections on how to start bot
Studio-Yandex-Practicum/coliving_bot pull request #25
Opened 2023-12-22 12:23 UTC by NechepurenkoA

Добавил пункты по запуску Telegram бота.

2023-12-22 15:37 UTC, TomatoInOil requested changes

2023-12-22 15:37 UTC, TomatoInOil commented on README.md
> +```shell
Здесь можно добавить, что нужно открыть ещё один терминал, т. к. после `python manage.py runserver` не получится ввести следующие команды

2023-12-22 15:37 UTC, TomatoInOil commented on README.md
> +```
`python run_bot.py`

2023-12-22 15:39 UTC, NechepurenkoA commented on README.md
> +```
Сам писал и сам напутал

2023-12-23 09:19 UTC, TomatoInOil approved these changes

2023-12-23 09:19 UTC, merged