v1app
Studio-Yandex-Practicum/coliving_bot pull request #40
Opened 2024-01-16 17:59 UTC by Vlad540700

Проверьте, пожалуйста, ручку location

2024-01-19 10:00 UTC, TomatoInOil requested changes
Нужно исправить ошибки, [указанные линтером ](https://github.com/Studio-Yandex-Practicum/coliving_bot/actions/runs/7545620608/job/20541657576?pr=40)
Можно покрыть минимальными тестами: проверка кода состояния, проверка формирования ответа - поля и значения соответствуют ожидаемым, проверка состояния (идемпотентность)

2024-01-23 07:49 UTC, TomatoInOil requested changes

2024-01-23 07:49 UTC, TomatoInOil commented on src/backend/profiles/tests.py
> +from rest_framework.test import APIClient
Можно использовать `APITestCase` из `DRF`, тогда не нужно будет переопределять `self.client`
https://www.django-rest-framework.org/api-guide/testing/#api-test-cases

2024-01-23 07:49 UTC, TomatoInOil commented on src/backend/profiles/tests.py
> +        response = self.client.get('/api/v1/locations/')
Здесь и далее можно использовать `reverse()`, чтобы после изменения урла не пришлось переписывать это в каждом тесте
https://docs.djangoproject.com/en/5.0/ref/urlresolvers/#reverse

2024-01-23 07:49 UTC, TomatoInOil commented on src/backend/profiles/tests.py
> +        data2 = json.loads(response2.content.decode('utf-8'))
После изменения `TestCase` на `APITestCase` будет проще всего использовать `response.data`
https://www.django-rest-framework.org/api-guide/testing/#testing-responses

2024-01-23 07:49 UTC, TomatoInOil commented on src/backend/profiles/tests.py
> +        self.assertEqual(response2.status_code, status.HTTP_200_OK)
Необязательно проверять здесь коды ответов, потому что у нас уже есть отдельный тест на это.

2024-01-23 07:49 UTC, TomatoInOil commented on src/backend/profiles/tests.py
> +        self.assertContains(response, 'Location 2')
После изменения `TestCase` на `APITestCase` и использования `response.data`
Можно это сделать одним ассертом `self.assertEqual(response.data, [{id: 1, name: "Location 1"}, ...])`

2024-01-24 18:29 UTC, Vlad540700 commented on src/backend/profiles/tests.py
> +from rest_framework.test import APIClient
исправил

2024-01-24 18:30 UTC, Vlad540700 commented on src/backend/profiles/tests.py
> +        response = self.client.get('/api/v1/locations/')
исправил

2024-01-24 18:30 UTC, Vlad540700 commented on src/backend/profiles/tests.py
> +        data2 = json.loads(response2.content.decode('utf-8'))
исправил

2024-01-24 18:30 UTC, Vlad540700 commented on src/backend/profiles/tests.py
> +        self.assertEqual(response2.status_code, status.HTTP_200_OK)
исправил

2024-01-24 18:30 UTC, Vlad540700 commented on src/backend/profiles/tests.py
> +        self.assertContains(response, 'Location 2')
исправил

2024-01-25 11:39 UTC, TomatoInOil commented
Изменения будут смёржены вместе с другим PR.

2024-01-25 11:39 UTC, closed without merging