Feature/report tests
Studio-Yandex-Practicum/coliving_bot pull request #41
Opened 2024-01-17 20:18 UTC by VDronovVladislav

Создал тесты для сериализаторов UserReportSerializer, MatchListSerializer и view-классов UserReportCreateView, MatchedUsersListView.

2024-01-19 09:08 UTC, TomatoInOil requested changes
Отлично, но я бы кое-что добавил

2024-01-19 09:08 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
Ещё т.к. в `MatchedUsersListView` переопределён метод `get_queryset(self)`, можно протестировать корректно ли формируется вывод.
https://lucid.app/documents/view/d96c293e-682e-4aa3-8054-c4f2b438d89e
Корректное поведение: когда для пользователя выводятся те, которых пользователь лайкнул, а они в ответ его тоже (`status=MatchStatuses.is_match`), а также тех, кто лайкнул пользователя, а он ответил тем же (`status=MatchStatuses.is_match`). 
Для этого можно в качестве тестовых данных создать трёх пользователей с профилями, подготовить два `MatchRequest`, которые отражают оба случая, и протестировать
- Без создания MatchRequest получаем пустой список
- Создавая первый случай, получаем список с соответствующим пользователем
- Создавая второй случай, получаем список с соответствующим пользователем
- Создавая оба случая, получаем список и с тем и с другим пользователем

Ещё один негативный тест:
Т.к. мы получаем список пользователей, для которых произошли совпадения лайков, то можно проверить, что выводятся именно они, а не все `MatchRequest`, для этого достаточно создать `MatchRequest` со статусом отличным от `is_match`, далее проверив, что выводится пустой список.

2024-01-19 21:13 UTC, VDronovVladislav commented on src/backend/search/tests/test_views.py
Привет. Все сделал, но потребовалось 5 объектов пользователя и 3 объекта мэтча. 
Для чего:
При создании первого мэтча (первый пользователь подписан на второго), второго мэтча (второй на первого). Мы получим для первого пользователя - данные второго, для второго - данные первого. Для третьего пользователя мы получим пустой список т.к он не подписан ни на кого. В данном сценарии список и с тем и с другим пользователем мы не получим никак.

* При этом вариант: Первый подписан на второго, второй на первого и третий на первого даст нам:
Для первого пользователя как раз оба случая (выведет его лайк и того, кто лайкнул его самого).
Для двух других - первого пользователя. То есть не получим пустой список. 

Поэтому были добавлены еще 2 пользователя. 4ый - не подписан ни на кого - для теста пустого списка.
Пятый - подписался на 1го, но статус - is_rejected - негативный сценарий - выводится пустой список.

Также был косяк в методе get_queryset для MatchedUsersListView. 
При сценарии, описанном тут * - для второго пользователя, который подписан на первого, а первый в ответ на него - выводился первый пользователь два раза (т.к на первого теперь подписан и третий). Тут return (users_who_sent_like | liked_users).all() - выводит данные некорректно. Если на пользователя 1 подписан пользователь 2 и наоборот, но при этом на пользователя 1 подписаны еще 5 человек, то для пользователя 2 он выведет пользователя 1 целых 6 раз.
return исправил c all() на distinct() - это решает проблему.

2024-01-23 08:20 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +        response = self.client.post(reverse("report"), self.report_data, format="json")
Вместо того, чтобы в каждом запросе передавать формат, можно определить его в настройках DRF
https://www.django-rest-framework.org/api-guide/testing/#setting-the-default-format

2024-01-23 14:58 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +        self.test_user_1 = UserFromTelegram.objects.create(telegram_id=1)
Это может ускорить выполнение тестов:
https://github.com/Studio-Yandex-Practicum/coliving_bot/pull/42#discussion_r1463403922

2024-01-24 18:12 UTC, VDronovVladislav commented on src/backend/search/tests/test_views.py
> +        response = self.client.post(reverse("report"), self.report_data, format="json")
Done

2024-01-24 18:35 UTC, VDronovVladislav commented on src/backend/search/tests/test_views.py
> +        self.test_user_1 = UserFromTelegram.objects.create(telegram_id=1)
Done

2024-01-30 05:26 UTC, merged