Реализована ручка создания профиля
Studio-Yandex-Practicum/coliving_bot pull request #42
Opened 2024-01-18 13:47 UTC by NASTY-SMIT

Все работает как по заданию, проверьте пожалуйста)

2024-01-21 15:29 UTC, ArtemKAF commented
1. Поле вьюсета `lookup_field` начнет работать так как нам нужно в паре с полем `lookup_url_kwarg`, если их правильно переопределить, то пропадает необходимость переопределять методы `get_object` и `get_queryset`.
Получается, что три строки с полями `queryset`, `lookup_field` и `lookup_url_kwarg` с правильными значениями сделают много строк кода лишними;
2. Класс `SlugRelatedField` для поля `location` в сериализаторе избавляет нас от необходимости в методе `perform_create` "колдовать" с городом (в проекте не предусматривается добавлять города через апи), тоже самое отнсится и к методу `perform_update` (этот метод и без нашего вмешательства прекрасно работает);
3. В методе `get_user` "не честно"  возвращать значение telegram_id из запроса. Необходимо его получить у объекта `obj`, а это коротенькая запись, которая не нуждается в дополнительной переменной и можно прямо в `return` прописать выражение для его получения.

2024-01-23 14:54 UTC, TomatoInOil requested changes

2024-01-23 14:54 UTC, TomatoInOil commented on src/backend/profiles/tests/test_profiles.py
> +            response = self.client.patch(
Здесь можно использовать `subTest()`
https://docs.python.org/3/library/unittest.html#distinguishing-test-iterations-using-subtests

2024-01-23 14:54 UTC, TomatoInOil commented on src/backend/profiles/tests/test_profiles.py
> +# python manage.py test profiles.tests.test_profiles.ProfileAPITestCase
Не забудь убрать комментарий

2024-01-23 14:54 UTC, TomatoInOil commented on src/backend/profiles/tests/test_profiles.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
Было бы хорошо айдишники вынести в константы
Пример:
```Python
TEST_TELEGRAM_ID=12345
EXISTING_PROFILE_TELEGRAM_ID=877877
NON_EXISTENT_PROFILE_TELEGRAM_ID=99999
```

2024-01-23 14:54 UTC, TomatoInOil commented on src/backend/profiles/tests/test_profiles.py
> +        UserFromTelegram.objects.create(telegram_id=12345)
Здесь можно использовать `setUpTestData`
https://docs.djangoproject.com/en/5.0/topics/testing/tools/#django.test.TestCase.setUpTestData
https://stackoverflow.com/questions/29428894/django-setuptestdata-vs-setup
> `setUpTestData()` is called once at the beginning of the test run for class-level setup. You'd use this to create objects that aren't going to be modified or changed in any of the test methods.
`setUp()` is called before every test function to set up any objects that may be modified by the test (every test function will get a "fresh" version of these objects).
>
> https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing#test_structure_overview

2024-01-25 10:57 UTC, TomatoInOil approved these changes

2024-01-25 10:57 UTC, merged