#39 добавлен логер в джангу
Studio-Yandex-Practicum/coliving_bot pull request #47
Opened 2024-01-22 20:54 UTC by JuniorRF

я хер знает почему апишка изменилась...
либо это что автоматическое,

2024-01-23 08:47 UTC, TomatoInOil requested changes

2024-01-23 08:47 UTC, TomatoInOil commented on src/backend/coliving_bot/settings.py
> +            "class": "logging.FileHandler",
Давай использовать `TimedRotatingFileHandler` с такими же настройками, что и в боте, можно через переменные окружения их связать, а значениями по умолчанию сделать:
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/bea42f7328b6158375318d514c5334725b88c7fd/src/bot/utils/configs.py#L23-L26

2024-01-23 17:00 UTC, ArtemKAF commented
Я бы предложил попробовать реализовать вариант с выбором файла настроек в зависимости от того в какм режиме работает бэк в режиме разработки или на продакшене.
И в настройках для разработки добавлять:
```python
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
```
в раздел `loggers` для того, чтобы видеть все SQL запросы к БД, которые происходят. Удобно для того, чтобы оптимизировать queryset-ы.

2024-01-23 18:02 UTC, JuniorRF commented
> Я бы предложил попробовать реализовать вариант с выбором файла настроек в зависимости от того в какм режиме работает бэк в режиме разработки или на продакшене. И в настройках для разработки добавлять:
> 
> ```python
>         'django.db.backends': {
>             'level': 'DEBUG',
>             'handlers': ['console'],
>         },
> ```

"filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },

в инструкции есть такое, но пока не очень понимаю, что меняется

>  видеть все SQL запросы к БД

для этого разве не джанго тулбар, для разработки самое то.

2024-01-23 18:25 UTC, JuniorRF commented on src/backend/coliving_bot/settings.py
> +            "class": "logging.FileHandler",
> TimedRotatingFileHandler
интернет говорит не работает TimedRotatingFileHandler в джанго...
какие то инструкции или альтернативные варианты предлагает интернет.
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/39898879/2b729fb4-a4e8-4bec-a3ee-c74d5412a883)

2024-01-23 20:47 UTC, JuniorRF commented on src/backend/coliving_bot/settings.py
> +            "class": "logging.FileHandler",
> Давай использовать `TimedRotatingFileHandler`

`"file": {
            "level":  os.getenv("LOGGING_LEVEL"),
            "class": TimedRotatingFileHandler,
            "filename": BASE_DIR.parent / ".data/logs/django.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 14,
            "encoding": "utf-8",
            "formatter": "verbose",
        },`

вот так ошибки не валятся))
ты имеешь  ввиду так?
конечно всю инфу спрячу переменные среды

2024-01-23 21:23 UTC, JuniorRF commented on src/backend/coliving_bot/settings.py
> +            "class": "logging.FileHandler",
Точно работает!!!
в консоли:
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Dev\\coliving_bot\\src\\.data\\logs\\django
.log' -> 'C:\\Dev\\coliving_bot\\src\\.data\\logs\\django.log.2024-01-23'

2024-01-24 16:10 UTC, JuniorRF commented
> ```python
>         'django.db.backends': {
>             'level': 'DEBUG',
>             'handlers': ['console'],
>         },

поковырял по советам из оф документации .
только сломал...

2024-01-27 09:06 UTC, JuniorRF commented
TimedRotatingFileHandler !
значения в переменных окружения!

2024-01-29 13:50 UTC, TomatoInOil requested changes

2024-01-29 13:50 UTC, TomatoInOil commented on src/backend/coliving_bot/settings.py
Можно сделать несколько настроек: для тестового сервера (`dev.py`), где расположить настройку логирования, которая сейчас у тебя написана, и локальные, где настроить логирование для дебага только в консоль 
(`local.py`) (https://github.com/Studio-Yandex-Practicum/coliving_bot/pull/47#issuecomment-1906516485), а общие настройки расположить в отдельный файл `base.py`, всё это поместив в новую директорию `src/backend/coliving_bot/settings`. Вот пример:
https://github.com/Studio-Yandex-Practicum/Lubimovka_backend/tree/develop/config/settings
- Важно изменить здесь строку `"coliving_bot.settings"` на новый путь к настройкам `"coliving_bot.settings.local"`
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/641d1c90080f2c5cabe93b67ec855999e301079c/src/backend/manage.py#L7
- А в `env.example` добавить запись о том, что эту настройку можно задать
```
# Файл настроек для бекенда можно переопределить
# DJANGO_SETTINGS_MODULE=coliving_bot.settings.local
```

2024-02-01 17:50 UTC, JuniorRF commented
не понимаю, почему коммит [a262e24](https://github.com/Studio-Yandex-Practicum/coliving_bot/pull/47/commits/a262e249c1525a3b2849ee50dab97ca479dd0d08) отображается не последним

2024-02-05 14:09 UTC, TomatoInOil approved these changes

2024-02-05 14:10 UTC, merged