add django project
Studio-Yandex-Practicum/coliving_bot pull request #6
Opened 2023-12-08 11:34 UTC by bbv-87

Создал django проект и добавил приложение "api"
проверьте пожалуйста

2023-12-08 11:44 UTC, TomatoInOil requested changes

2023-12-08 11:44 UTC, TomatoInOil commented on src/backend/coliving_bot/coliving_bot/settings.py
> +USE_SQLITE = True
Думаю, стоит вынести это в переменные окружения, как и SECRET_KEY, и DEBUG

2023-12-08 11:44 UTC, TomatoInOil commented on src/backend/coliving_bot/coliving_bot/settings.py
> +        "PORT": os.getenv("DB_PORT"),
Будет хорошо добавить `.env.example` в корневой директории проекта и перечислить там все переменные окружения, которые здесь используются, чтобы другие разработчики понимали, как заполнить `.env`

2023-12-08 14:04 UTC, TomatoInOil approved these changes

2023-12-08 14:24 UTC, TomatoInOil requested changes

2023-12-08 14:24 UTC, TomatoInOil commented on src/backend/coliving_bot/coliving_bot/settings.py
>  if USE_SQLITE:
Попробуй прописать в `.env`
```
USE_SQLITE=False
```
В этом случае всё равно будет использоваться `SQLite`, это происходит потому, что в `USE_SQLITE `при чтении с помощью `os.getenv()` записывается строка `"False"`, поэтому конструкция `if` отрабатывает по положительной ветви 
Один из способов исправить это
Задать явно значение, которое будет означать `True`
```Python
USE_SQLITE = os.getenv("USE_SQLITE", False) == "True"
```
Также предлагаю указать значение по умолчанию, тоже самое сделать для `DEBUG`

2023-12-08 14:49 UTC, bbv-87 commented on src/backend/coliving_bot/coliving_bot/settings.py
>  if USE_SQLITE:
Спасибо,
упустил из виду

2023-12-09 14:28 UTC, TomatoInOil approved these changes

2023-12-09 14:35 UTC, merged