Api documentation
Studio-Yandex-Practicum/coliving_bot pull request #65
Opened 2024-02-13 09:36 UTC by Ozxar69

добавлена api документация по ссылкам:
http://127.0.0.1:8000/api/schema/redoc/

http://127.0.0.1:8000/api/schema/swagger-ui/

2024-02-16 10:08 UTC, TomatoInOil requested changes

2024-02-16 10:08 UTC, TomatoInOil commented on src/backend/coliving_bot/settings/base.py
>  }
Будет хорошо добавить такую настройку, чтобы ручки делились по тегам
```Python
"SCHEMA_PATH_PREFIX": "/api/v1"
```

2024-02-16 19:33 UTC, Ozxar69 commented on src/backend/coliving_bot/settings/base.py
>  }
Добавил

2024-02-17 08:23 UTC, TomatoInOil approved these changes

2024-02-17 08:24 UTC, merged