Feature/attaching user to koliving
Studio-Yandex-Practicum/coliving_bot pull request #68
Opened 2024-02-14 14:35 UTC by AnnaKotovapr

2024-02-17 09:42 UTC, TomatoInOil requested changes
Отлично, но есть, что поправить

2024-02-17 09:42 UTC, TomatoInOil commented on src/backend/profiles/urls.py
> +    ),
Можно назвать `users-detail` для консистентности с остальными ручками

2024-02-17 09:42 UTC, TomatoInOil commented on src/backend/profiles/tests/test_colivings.py
Было бы хорошо вынести тесты по твоей ручке в отдельный `UserResidenceUpdateAPITestCase`, а не дополнять класс, который тестирует другую ручку. Это улучшит структурирование и читаемость наших тестов.

2024-02-17 09:42 UTC, TomatoInOil commented on src/backend/profiles/tests/test_colivings.py
> +        invalid_residence_id = 999999  # Несуществующий ID коливинга
Комментария можно избежать, если вынести `999999` в константу с понятным именем, например, `INVALID_COLIVING_ID` или `NON_EXISTENT_COLIVING_ID`.
Здесь тоже
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/95c2daf1f56faf38fabb7138112442bd9b5b2013/src/backend/profiles/tests/test_colivings.py#L166

2024-02-17 09:42 UTC, TomatoInOil commented on src/bot/internal_requests/service.py
> +        response.raise_for_status()
Для избежания дублирования кода предлагаю использовать здесь метод `_patch_request`, который уже реализован в классе.

2024-02-17 09:42 UTC, TomatoInOil commented on src/bot/internal_requests/service.py
> +        """
Для поддержания структуры и удобства чтения кода предлагаю разместить функции для внешнего использования (без подчеркивания) над функциями для внутреннего использования (с подчеркиванием). Такой порядок поможет лучше ориентироваться в классе. 

https://stackoverflow.com/a/8689983
"Чтение кода сверху вниз: правило понижения" https://habr.com/ru/articles/485118/

2024-02-17 14:59 UTC, AnnaKotovapr commented on src/backend/profiles/tests/test_colivings.py
Да, но тогда придется повторить большой кусок кода, что нарушает принцип DRY:

@classmethod
    def setUpTestData(cls):
        Coliving.objects.create(
            host=UserFromTelegram.objects.create(telegram_id=OWNER_1_TELEGRAM_ID),
            price=2500,
            room_type="Комната",
            location=Location.objects.create(name="Москва"),
            about="Уютное пространство...",
        )
        Coliving.objects.create(
            host=UserFromTelegram.objects.create(telegram_id=OWNER_2_TELEGRAM_ID),
            price=2500,
            room_type="Комната",
            location=Location.objects.create(name="Санкт-Петербург"),
            about="Небольшая",

2024-02-20 14:30 UTC, TomatoInOil commented on src/backend/profiles/tests/test_colivings.py
@AnnaKotovapr 

Нарушение принципа DRY и дублирование кода не всегда одно и тоже. Представь ситуацию, что для тестирования одной ручки нам потребуется изменить тестовые данные, но ведь это повлияет на несвязанные тесты, которые используют эти же тестовые данные.

Если тебе не нравится, что это занимает 14 строк, то можно уменьшить до 6:
- В тестах твоей ручки используется по 1 экземпляру `UserFromTelegram`, `Coliving`, поэтому нет надобности создавать 2 коливинга с разными владельцами.  

Можно также использовать константы из моделей `ColivingTypes.ROOM` и `Restrictions.PRICE_MIN`, чтобы не хардкодить. 
```Python
Coliving.objects.create(
    host=UserFromTelegram.objects.create(telegram_id=cls.OWNER_TELEGRAM_ID),
    price=Restrictions.PRICE_MIN + 1,
    room_type=ColivingTypes.ROOM,
    location=Location.objects.create(name=cls.LOCATION_NAME),
)
```

2024-02-21 12:35 UTC, TomatoInOil approved these changes

2024-02-21 12:36 UTC, merged