post request function to match_requests url  was added
Studio-Yandex-Practicum/coliving_bot pull request #74
Opened 2024-02-17 10:53 UTC by Ilya-Cheb0503

Добавил функцию send_match_request.
Однако не проверял корректность.

2024-02-17 10:59 UTC, TomatoInOil requested changes

2024-02-17 10:59 UTC, TomatoInOil commented on src/bot/internal_requests/service.py
> +        :param receiver: id получателя.
Можно уточнить, что это именно `telegram_id`, а не `pk`

2024-02-17 10:59 UTC, TomatoInOil commented on src/bot/internal_requests/service.py
> +        endpoint_urn = "match-request/"
Упустил `s`
"match-request`s`/"

2024-02-17 16:22 UTC, Ilya-Cheb0503 commented on src/bot/internal_requests/service.py
> +        :param receiver: id получателя.
Изменено ✅

2024-02-17 16:22 UTC, Ilya-Cheb0503 commented on src/bot/internal_requests/service.py
> +        endpoint_urn = "match-request/"
Добавлено ✅

2024-02-17 16:24 UTC, Ilya-Cheb0503 commented
changed "id" to "telegram_id" and "request" to "requests"

2024-02-21 12:37 UTC, TomatoInOil commented on src/bot/internal_requests/service.py
> +
https://github.com/Studio-Yandex-Practicum/coliving_bot/pull/68#discussion_r1493287679

2024-02-21 16:59 UTC, TomatoInOil approved these changes

2024-02-21 17:00 UTC, merged