Feature/profile search impr
Studio-Yandex-Practicum/coliving_bot pull request #81
Opened 2024-02-22 07:12 UTC by ilililililililililililililil

If apply these commits will:
- Add several fixes and improvements for EP /api/v1/profiles/ profiles 
- Add tests for EP /api/v1/profiles/ profiles search

2024-02-23 19:22 UTC, ilililililililililililililil commented
@TomatoInOil посмотри пожалуйста PR

2024-02-25 13:01 UTC, TomatoInOil requested changes
В основном рекомендации направлены на уменьшение ненужного дублирования в коде и улучшение его читаемости, поддерживаемости. 

Если говорить про тесты, то в `global_search_results_data` есть случай, в котором тесты проверяют, что профиль `viewer` не попадает в ответ, но лично мне захотелось бы добавить тест, который проверят это более явно, исключив влияние остальных фильтров. 
Например, передав в kwargs только viewer 
`response = self.client.get(self.url_reverse, dict(viewer=viewer_telegram_id))`
И с помощью `assertNotIn` проверить, что переданный `viewer_telegram_id` не попадает в `[profile["user"] for profile in response.json()]`

2024-02-25 13:01 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +        cls.sex_f = "Девушка"
Будет хорошо использовать этот класс:
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/59334ad503d35a98e80cd7ab299fac8184ce4ceb/src/backend/profiles/constants.py#L13-L19
Заменив на `Sex.MAN`, `Sex.WOMAN`, там где `cls.sex_m`, `cls.sex_f`, `self.sex_m`, `self.sex_f`.

2024-02-25 13:01 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +        cls.test_user_10 = UserFromTelegram.objects.create(telegram_id=10)
Здесь можно использовать [list comprehension](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions) и далее получать пользователей по индексу.
```Python
test_users = [UserFromTelegram.objects.create(telegram_id=id) for id in range(1, 11)]

# Использование
test_users[0]
```

2024-02-25 13:01 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +        )
Можно определить кортеж тестовых данных со значениями полей, перебрав их, создать профили, используя тот же list comprehension. 
```Python
ProfileTestData = namedtuple("ProfileTestData", ["user", "name", "age", "location", "sex"])

# ...

profiles_data = (
    ProfileTestData(test_users[0], "Name_1", 21, cls.location_m, Sex.MAN),
    ProfileTestData(test_users[1], "Name_2", 25, cls.location_m, Sex.MAN),
    # И тд
)
test_profiles = [
    Profile.objects.create(**data._asdict()) for data in profiles_data
]
```

2024-02-25 13:01 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +        }
Здесь дублируется то, что мы передаём при создании профиля, но для отдельных пользователей. Так почему бы нам не использовать сами профили, а не их вводные данные? Нам же нужно проверить корректность фильтрации, а не сериализации полей. 
```Python
cls.expected_search_data_2 = {
    "search_criteria": {
        "location": cls.LOCATION_M_NAME,
        "sex": Sex.WOMAN,
        "age_min": "30",
        "age_max": "40",
    },
    "search_result": [
        ProfileSerializer(test_profiles[3]).data,
        ProfileSerializer(test_profiles[4]).data,
    ],
}
```

2024-02-25 13:01 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +    empty_match_data = []
Далее идёт повторное определение в `def setUpTestData(cls)`, нужно оставить что-то одно. При наименовании констант используется upper-case https://stackoverflow.com/a/45702782
Но есть другая проблема, эта константа не используется далее в тестах.

2024-02-25 13:01 UTC, TomatoInOil commented on src/backend/search/tests/test_views.py
> +            {"location": "S", "sex": cls.sex_f, "age_min": "40", "age_max": "50"},
Хорошо будет вынести названия городов в константы класса.

2024-02-25 13:01 UTC, TomatoInOil commented on src/backend/search/views.py
> +            excl_list.append(viwed.pk)
1. Вместо того, чтобы совершать ещё один запрос к БД `Profile.objects.get(pk=user.pk)`, можно использовать в фильтрации условие, где поле `user` в профиле соответствует `user`, полученному из параметра `viewer`
```Python
Q(user=user)
```
2. Используя оператор [| (OR)](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#or) можно объединить эти два `queryset` при фильтрации в один
```Python
Profile.objects.filter(
    Q(user=user) | Q(viewers=user)
)
```
3. Вместо цикла для формирования списка с pk можно использовать [.values_list()](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#values-list)

Применив всё это, получим:
```Python
excl_list = Profile.objects.filter(
    Q(user=user) | Q(viewers=user)
).values_list("pk", flat=True)
```

2024-02-25 19:04 UTC, ilililililililililililililil commented on src/backend/search/tests/test_views.py
> +    empty_match_data = []
это не было константой, лишний текст

2024-02-26 05:49 UTC, TomatoInOil approved these changes

2024-02-26 05:49 UTC, merged