Feature/deleting an old photo
Studio-Yandex-Practicum/coliving_bot pull request #82
Opened 2024-02-24 17:27 UTC by AnnaKotovapr

Что сделано?

Сейчас можно добавлять сколько угодно фото и удалять фото по одному при обращении по pk, протестировала в браузерной строке

2024-02-26 10:18 UTC, ArtemKAF commented on src/backend/images/api_views.py
> +    def destroy(self, request, *args, **kwargs):
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/205767ff3b783c6ff1c46ba6e5e20a4a83911c8b/src/backend/images/api_views.py#L80-L86

В чем смысл этих строк, если эти методы символ в символ наследуются от generics.DestroyAPIView?
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/205767ff3b783c6ff1c46ba6e5e20a4a83911c8b/src/backend/images/api_views.py#L21

Который наследует методы destroy и perform_destroy от mixins.DestroyModelMixin

2024-02-26 10:39 UTC, ArtemKAF commented on src/bot/internal_requests/service.py
> +        if response.status_code == 204:
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/205767ff3b783c6ff1c46ba6e5e20a4a83911c8b/src/bot/internal_requests/service.py#L126-L129

В рабочем проекте это лишнее.
Ошибки будут в виде исключений сгенерированы здесь:
https://github.com/Studio-Yandex-Practicum/coliving_bot/blob/205767ff3b783c6ff1c46ba6e5e20a4a83911c8b/src/bot/internal_requests/service.py#L141 и обработаны соответствующим хэндлером.
А сообщение об успешном удалении изображения нет необходимости выводить в консоль с помощью print-а.

2024-03-02 10:14 UTC, TomatoInOil requested changes

2024-03-02 10:14 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +        return States.ABOUT_YOURSEL
Опечатка

2024-03-02 10:27 UTC, TomatoInOil approved these changes

2024-03-02 10:27 UTC, merged