Feature/cancellation of application form
Studio-Yandex-Practicum/coliving_bot pull request #85
Opened 2024-02-28 10:57 UTC by Ozxar69

В профиле созданы все значения кнопки Отмена, создана функция отмены диалога, создана функция которая объединяет клавиатуры, добавляя к любому списку местожительств (или полов) в конец кнопку Отмены, на любом этапе кроме загрузки фото кнопка работает, выполняет свою функцию, при использовании отправляет сообщение пользователю и исчезает.

2024-03-02 11:22 UTC, TomatoInOil requested changes
Ветка коливинга тоже нуждается в этих изменениях `src/bot/conversations/coliving`

2024-03-02 11:22 UTC, TomatoInOil commented on src/bot/conversations/profile/callback_funcs.py
> +    return ConversationHandler.END
Хорошо бы отчищать контекст перед выходом из диалога.
```python
context.user_data.clear()
```

2024-03-04 11:39 UTC, Ozxar69 commented
Upd. Создана директория для кнопок общего назначения, в нее перемещены все необходимые функции и константы для кнопки Отмена, Из common_functions кнопка отмены импортирована в профиль и в колливинг. Комментарии учтены.

2024-03-07 17:56 UTC, TomatoInOil approved these changes

2024-03-07 17:57 UTC, merged