Feature/expanding the profile editing functionality
Studio-Yandex-Practicum/coliving_bot pull request #87
Opened 2024-02-28 18:40 UTC by Ilya-Cheb0503

the branch was renamed

2024-02-28 18:45 UTC, Ilya-Cheb0503 commented
And the task was completed. Now it is waiting for the review

2024-03-02 11:50 UTC, TomatoInOil requested changes
Когда ты создавал новую ветку, видимо либо ответвлялся от своей старой, либо не спуллил последние изменения, которые внесли другие разработчики. Выполни `git pull origin develop`, находясь в этой ветке, исправь возникшие конфликты при слиянии, убедись, что бот запускается, что твои улучшения работают, как задумано

2024-03-02 11:50 UTC, TomatoInOil commented on src/bot/conversations/profile/states.py
Добавляя здесь состояния, нужно увеличить значение в `range()`

`ValueError: not enough values to unpack (expected 18, got 14)`

2024-03-02 11:50 UTC, TomatoInOil commented on src/bot/conversations/profile/buttons.py
![image](https://github.com/Studio-Yandex-Practicum/coliving_bot/assets/93451214/a9aae42d-fc72-416c-82a2-1156fe6984e3)
Нужно также изменить эту клавиатуру в `src/bot/conversations/profile/keyboards.py`

2024-03-08 15:01 UTC, TomatoInOil approved these changes

2024-03-08 15:01 UTC, merged